### ISSUE TITLE
Using V5.0.1 for Lumen - error at OAuth2ServerServiceProvider.php:111

### ISSUE THREAD

**Issue by Twisterking** [lucadegasperi/oauth2-server-laravel#563]
So after reading some of the issus on here I decided to use the newest version of your library for my Lumen project. I'm completely new to Laravel and Lumen so please bear with me.

So after following [this tutorial](http://esbenp.github.io/2015/05/26/lumen-web-api-oauth-2-authentication/) and also [reading this](https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Lumen-Installation) I ran into this error:
```
exception 'ErrorException' with message 'explode() expects parameter 2 to be string, object given' in /Users/Patrick/dev/apitest/vendor/lucadegasperi/oauth2-server-laravel/src/OAuth2ServerServiceProvider.php:111
```

I then checked the tutorial of esbenp again and found out, that he used the version 4.0.2. Checking the code I found out, that in line 111
```
$grant->setVerifyCredentialsCallback($grantParams['callback']);
```
was replaced by
```
list($className, $method) = array_pad(explode('@', $grantParams['callback']), 2, 'verify');
$verifier = $app->make($className);
$grant->setVerifyCredentialsCallback([$verifier, $method]);
```
in 5.0.1.

After replacing this code with the old version again it all works like a charm. Any ideas on this?

PS: sidenote: In your wiki you still use `"lucadegasperi/oauth2-server-laravel": "~4.1@dev"`, which returns a composer error! please fix!

**Comment by vinkla** [comment]
First, if you're using Lumen you've to use the latest version of this library which is currently on 5.0. I've updated the docs.

**Comment by Twisterking** [comment]
After some more fiddling around I got it to work! :-)
The problem was, that in the tutorial the callback function for the password grant was defined directly in the `config/oauth2.php` file. This is what broke the whole thing. For a noob like me it took me sme time to figure that out. After solving it like [shown here](https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Implementing-an-Authorization-Server-with-the-Password-Grant), it works now!

Maybe the part at line 111 can be solved somehow that both callback definitions work?!

Thanks for updating the docs!

**Comment by vinkla** [comment]
Glad you solved it! Since 5.0 you can't use callbacks anymore. Sorry.

**Comment by michaeltansy** [comment]
After reading what Twisterking did, I still dont solve it. I got this error 
Argument 1 passed to League\OAuth2\Server\Grant\PasswordGrant::setVerifyCredentialsCallback() must be callable, array given
while it is being called in
oauth2-server-laravel\src\OAuth2ServerServiceProvider.php on line 124 and defined
Please somebody help me to solve this

**Comment by vinkla** [comment]
Please open a new issue if you've any questions. Your comment will get lost and we wont be able to help you if you post on old closed issues.

**Comment by michaeltansy** [comment]
okay I already did, sorry for spamming
