### ISSUE TITLE
Conflict with symphony version?

### ISSUE THREAD

**Issue by rhufsky** [lucadegasperi/oauth2-server-laravel#634]
Trying to create a Laravel 5.2 project with oauth2 I create the project using 
`laravel new myProject`

Integrating oauth2-server-laravel using composer gives me a lot of messages pointing at conflicts with other laravel components, see below.

Am I doing something wrong?

```
$ composer require "lucadegasperi/oauth2-server-laravel: ^5.1"
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install lucadegasperi/oauth2-server-laravel 5.1.1
    - Conclusion: remove symfony/http-foundation v3.0.1
    - Installation request for lucadegasperi/oauth2-server-laravel  ^5.1 -> satisfiable by lucadegasperi/oauth2-server-laravel[5.1.0, 5.1.1].
    - Conclusion: don't install symfony/http-foundation v3.0.1
    - lucadegasperi/oauth2-server-laravel 5.1.0 requires league/oauth2-server 4.1.* -> satisfiable by league/oauth2-server[4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4].
    - league/oauth2-server 4.1.1 requires symfony/http-foundation ~2.4 -> satisfiable by symfony/http-foundation[v2.4.0, v2.4.1, 
....
```

**Comment by sixlive** [comment]
Same problem here with Laravel 5.2.*

```
Search for a package: lucadegasperi/oauth2-server-laravel
Enter the version constraint to require (or leave blank to use the latest version): 5.1.*
Search for a package:
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install lucadegasperi/oauth2-server-laravel 5.1.1
    - Conclusion: remove symfony/http-foundation v3.0.1
    - Installation request for lucadegasperi/oauth2-server-laravel 5.1.* -> satisfiable by lucadegasperi/oauth2-server-laravel[5.1.0, 5.1.1].
    - Conclusion: don't install symfony/http-foundation v3.0.1
    - lucadegasperi/oauth2-server-laravel 5.1.0 requires league/oauth2-server 4.1.* -> satisfiable by league/oauth2-server[4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4].
    - league/oauth2-server 4.1.1 requires symfony/http-foundation ~2.4 -> satisfiable by symfony/http-foundation[v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.8.0, v2.8.1].
    - league/oauth2-server 4.1.2 requires symfony/http-foundation ~2.4 -> satisfiable by symfony/http-foundation[v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.8.0, v2.8.1].
    - league/oauth2-server 4.1.3 requires symfony/http-foundation ~2.4 -> satisfiable by symfony/http-foundation[v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.8.0, v2.8.1].
    - league/oauth2-server 4.1.4 requires symfony/http-foundation ~2.4 -> satisfiable by symfony/http-foundation[v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.8.0, v2.8.1].
    - league/oauth2-server 4.1.0 requires symfony/http-foundation ~2.5 -> satisfiable by symfony/http-foundation[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.8.0, v2.8.1].
    - Can only install one of: symfony/http-foundation[v2.8.0, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.8.1, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.4.0, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.4.1, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.4.10, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.4.2, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.4.3, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.4.4, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.4.5, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.4.6, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.4.7, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.4.8, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.4.9, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.5.0, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.5.1, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.5.10, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.5.11, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.5.12, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.5.2, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.5.3, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.5.4, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.5.5, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.5.6, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.5.7, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.5.8, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.5.9, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.6.0, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.6.1, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.6.10, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.6.11, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.6.12, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.6.2, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.6.3, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.6.4, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.6.5, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.6.6, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.6.7, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.6.8, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.6.9, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.0, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.1, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.2, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.3, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.4, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.5, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.6, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.7, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.8, v3.0.1].
    - Installation request for symfony/http-foundation == 3.0.1.0 -> satisfiable by symfony/http-foundation[v3.0.1].
```

**Comment by vinkla** [comment]
Confirmed, I've opened an issue at the `leage/oauth2-server` package. Thanks for reporting!

**Comment by vinkla** [comment]
This should be solved now in [4.1.5](https://github.com/thephpleague/oauth2-server/releases/tag/4.1.5). Run `composer update` in order to fix this.

**Comment by sixlive** [comment]
Awesome thanks!!

**Comment by rhufsky** [comment]
Thanks a lot for this super fast fix, now it works like a charm!

**Comment by alissonmn** [comment]
Error not solved:

**1. composer.json**

    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "tinymce/tinymce": "^4.2",
        "guzzlehttp/guzzle": "^6.1",
        "barryvdh/laravel-ide-helper": "^2.1",
        "doctrine/dbal": "^2.5",
        "lucadegasperi/oauth2-server-laravel": "5.0.*"

**2. Console error**
_>composer update_
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.2.12
    - Conclusion: don't install laravel/framework v5.2.12
    - Conclusion: don't install laravel/framework v5.2.11
    - Conclusion: don't install laravel/framework v5.2.10
    - Conclusion: don't install laravel/framework v5.2.9
    - Conclusion: don't install laravel/framework v5.2.8
    - Conclusion: don't install laravel/framework v5.2.7
    - Conclusion: don't install laravel/framework v5.2.6
    - Conclusion: don't install laravel/framework v5.2.5
    - Conclusion: don't install laravel/framework v5.2.4
    - Conclusion: don't install laravel/framework v5.2.3
    - Conclusion: don't install laravel/framework v5.2.2
    - Conclusion: don't install laravel/framework v5.2.1
    - lucadegasperi/oauth2-server-laravel 5.0.0 requires illuminate/config 5.1.* -> satisfiable by illuminate/config[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1
.28, v5.1.6, v5.1.8].
    - lucadegasperi/oauth2-server-laravel 5.0.1 requires illuminate/config 5.1.* -> satisfiable by illuminate/config[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1
.28, v5.1.6, v5.1.8].
    - lucadegasperi/oauth2-server-laravel 5.0.2 requires illuminate/config 5.1.* -> satisfiable by illuminate/config[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1
.28, v5.1.6, v5.1.8].
    - lucadegasperi/oauth2-server-laravel 5.0.3 requires illuminate/config 5.1.* -> satisfiable by illuminate/config[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1
.28, v5.1.6, v5.1.8].
    - don't install illuminate/config v5.1.1|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.13|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.16|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.2|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.20|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.22|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.25|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.28|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.6|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.8|don't install laravel/framework v5.2.0
    - Installation request for laravel/framework 5.2.* -> satisfiable by laravel/framework[v5.2.0, v5.2.1, v5.2.10, v5.2.11, v5.2.12, v5.2.2, v5.2.3, v5.2.4, v5.2.5, v5.2.6, v5.2.7,
v5.2.8, v5.2.9].
    - Installation request for lucadegasperi/oauth2-server-laravel 5.0.* -> satisfiable by lucadegasperi/oauth2-server-laravel[5.0.0, 5.0.1, 5.0.2, 5.0.3].

**Comment by gmferreir1** [comment]
change
 "lucadegasperi/oauth2-server-laravel": "5.0.*"
to
 "lucadegasperi/oauth2-server-laravel": "5.1.*"

**Comment by cnBruceHong** [comment]
@gmferreir1 Thanks!

**Comment by alissonmn** [comment]
Thanks gmferrier1

**Comment by higorcampos** [comment]
VLWWWWWWWW :)
